"""Switch to association object for MealIngredient with amount_grams

Revision ID: 22dade51df7e
Revises: 079cabab51f2
Create Date: 2025-07-22 06:12:35.808313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dade51df7e'
down_revision: Union[str, Sequence[str], None] = '079cabab51f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ingredient_id'), 'ingredient', ['id'], unique=False)
    op.drop_index(op.f('ix_meal_ingredient_id'), table_name='meal_ingredient')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_meal_ingredient_id'), 'meal_ingredient', ['id'], unique=False)
    op.drop_index(op.f('ix_ingredient_id'), table_name='ingredient')
    # ### end Alembic commands ###
