"""Add nutrition fields to Meal

Revision ID: e2a19e6639ee
Revises: 22dade51df7e
Create Date: 2025-07-22 06:14:47.185019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a19e6639ee'
down_revision: Union[str, Sequence[str], None] = '22dade51df7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('calories', sa.Float(), nullable=False))
    op.add_column('meal', sa.Column('protein', sa.Float(), nullable=False))
    op.add_column('meal', sa.Column('fat', sa.Float(), nullable=False))
    op.add_column('meal', sa.Column('carbs', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'carbs')
    op.drop_column('meal', 'fat')
    op.drop_column('meal', 'protein')
    op.drop_column('meal', 'calories')
    # ### end Alembic commands ###
